### ISSUE TITLE
Very slow performance metadata

### ISSUE THREAD

**Issue by bekerov** [mapbox/rio-tiler#41]
I use python 3.6 and installed rio-tiler from repo.
And script run time is too high.

```
from aws_sat_api.search import landsat
from rio_tiler import landsat8
from datetime import datetime

startTime = datetime.now()

l8_path = 178
l8_row = 21
full_search = False
l8_meta = landsat(l8_path, l8_row, full_search)

metadata = landsat8.metadata('LC81780212013117LGN01', 5, 95)
print(metadata)

print(datetime.now() - startTime)

```

Output:

```
{'sceneid': 'LC81780212013117LGN01', 'bounds': [36.11826, 54.83456, 40.03735, 56.95001], 'rgbMinMax': {'1': [1489, 7031], '2': [1238, 7094], '3': [922, 6769], '4': [777, 7117], '5': [1278, 7794], '6': [811, 6038], '7': [474, 4849], '9': [17, 336], '10': [264, 285], '11': [261, 281]}}
0:03:00.593763
```

Please help.

**Comment by bekerov** [comment]
![image](https://user-images.githubusercontent.com/2405629/39629026-829f7e68-4fb3-11e8-9109-dc6f0d72ebbc.png)

**Comment by vincentsarago** [comment]
👋 @bekerov, `landsat8.metadata` take some time because it needs to get the previews to calculate min/max histogram cut. Depending on you network and how far form the aws `us-west-2` endpoint you are the `metadata` retrieval can be slow.
I you run this on a AWS service (ec2, ecs, lambda) on AWS us-west-2 region it should be quite fast. 

please feel free to close if the answer is 🆗
